package net.cumba.cdisc.core;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.Optional;

/**
 * Typed view over a rules directory's {@code packages.json} — the authoritative index that maps
 * each shipped package file to the {@code (family, standard, version)} tuple it holds. Generated by
 * the offline package assembler and copied alongside the {@code rules/} corpus; it is the single
 * source every reader (runtime rule selection, the REST run-form, the editor seeder, the corpus
 * tests) consults instead of parsing package file names.
 *
 * <p>
 * File names are not reversibly parseable — both standard names ({@code SENDIG-DART}) and versions
 * ({@code 3-1-1}) contain dashes — so lookup is always by manifest, never by splitting the name.
 * {@code family} / {@code standard} / {@code version} are stored in display form ({@code FDA},
 * {@code SDTMIG}, {@code 3.4}); {@link #find} and {@link #forStandardVersion} normalise both sides,
 * so a caller may pass either the display ({@code 3.4}) or the file-encoded ({@code 3-4}) version.
 * </p>
 */
public record RulePackageManifest(@JsonProperty("generatedFrom") String generatedFrom,
        @JsonProperty("packages") List<Entry> packages)
{

    /** The manifest file name, resolved inside a rules directory. */
    public static final String FILE_NAME = "packages.json";

    private static final ObjectMapper READER = new ObjectMapper()
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

    private static final ObjectMapper WRITER = new ObjectMapper()
            .enable(SerializationFeature.INDENT_OUTPUT);

    /** Null-safe canonicalisation of the components. */
    public RulePackageManifest
    {
        generatedFrom = generatedFrom == null ? "" : generatedFrom;
        packages = packages == null ? List.of() : List.copyOf(packages);
    }


    /** Convenience constructor for callers that don't set a provenance string. */
    public RulePackageManifest(List<Entry> packages)
    {
        this("rules-src", packages);
    }

    /**
     * One shipped package: its file name and the {@code (family, standard, version)} it holds, plus
     * the rule count (informational).
     */
    public record Entry(@JsonProperty("file") String file, @JsonProperty("family") String family,
            @JsonProperty("standard") String standard, @JsonProperty("version") String version,
            @JsonProperty("ruleCount") int ruleCount,
            @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY) @JsonProperty("standards") List<net.cumba.cdisc.core.model.StandardRef> standards)
    {

        /** Null-safe: an entry written before R6 (or by a custom generator) declares nothing. */
        public Entry
        {
            standards = standards == null ? List.of() : List.copyOf(standards);
        }


        /**
         * Convenience constructor for an entry that declares no library standards (the R6 array
         * defaults to empty). Keeps existing positional callers working.
         *
         * @param file
         *            the package file name
         * @param family
         *            the rule family, e.g. {@code CDISC}
         * @param standard
         *            the standard display name, e.g. {@code SDTMIG}
         * @param version
         *            the version display form, e.g. {@code 3.4}
         * @param ruleCount
         *            the package's rule count (informational)
         */
        public Entry(String file, String family, String standard, String version, int ruleCount)
        {
            this(file, family, standard, version, ruleCount, List.of());
        }
    }

    /**
     * Loads {@code <rulesDir>/packages.json}. Returns an EMPTY manifest when the file is absent, so
     * a custom rules directory that carries only explicit rule files (no generated manifest) still
     * degrades gracefully — matching the "no conventional file found → warn + skip" behaviour of
     * the prior filename-convention resolver. A present-but-malformed manifest still throws.
     *
     * @param rulesDir
     *            the rules directory (the same one a run resolves packages from)
     * @return the parsed manifest, or an empty manifest if {@code packages.json} is absent
     * @throws IOException
     *             if the manifest exists but cannot be read or parsed
     */
    public static RulePackageManifest load(Path rulesDir) throws IOException
    {
        Path path = rulesDir.resolve(FILE_NAME);
        if (!Files.exists(path))
        {
            return new RulePackageManifest(List.of());
        }
        try (InputStream in = Files.newInputStream(path))
        {
            return READER.readValue(in, RulePackageManifest.class);
        }
    }


    /**
     * Writes this manifest to {@code <rulesDir>/packages.json} as indented JSON with a trailing
     * newline (the canonical corpus serialisation). Shared by the assembler (stage 0) and the
     * expression-generator's copy-to-{@code rules/} step (stage 1).
     *
     * @param rulesDir
     *            the target rules directory
     * @throws IOException
     *             if the file cannot be written
     */
    public void writeTo(Path rulesDir) throws IOException
    {
        String json = WRITER.writeValueAsString(this) + "\n";
        Files.writeString(rulesDir.resolve(FILE_NAME), json, StandardCharsets.UTF_8);
    }


    /**
     * Case-insensitive lookup of the single package for one {@code (family, standard, version)}.
     * The version matches in either display ({@code 3.4}) or file-encoded ({@code 3-4}) form.
     *
     * @return the matching entry, or empty when no package covers the tuple
     */
    public Optional<Entry> find(String family, String standard, String version)
    {
        return packages.stream().filter(e -> eqTok(e.family(), family)
                && eqTok(e.standard(), standard) && eqTok(e.version(), version)).findFirst();
    }


    /** Every package for a family, any standard/version (empty when the family is unknown). */
    public List<Entry> forFamily(String family)
    {
        return packages.stream().filter(e -> eqTok(e.family(), family)).toList();
    }


    /**
     * Every family package for one {@code (standard, version)} — the UNION set. Used by whole-pack
     * consumers (the rule-test factories, the scenario trimmer, corpus-wide tests) that must see
     * all rules for a standard/version regardless of family. E.g. {@code (SDTMIG, 3.4)} → the four
     * {@code rules-{cdisc,core,fda,pmda}-sdtmig-3-4.json}; {@code (ADaMIG, 1.3)} → the two
     * {@code rules-{cdisc,pmda}-adamig-1-3.json}.
     */
    public List<Entry> forStandardVersion(String standard, String version)
    {
        return packages.stream()
                .filter(e -> eqTok(e.standard(), standard) && eqTok(e.version(), version)).toList();
    }


    /** Resolves each entry's file name against {@code rulesDir}. */
    public static List<Path> toPaths(Path rulesDir, List<Entry> entries)
    {
        return entries.stream().map(e -> rulesDir.resolve(e.file())).toList();
    }

    // ---- comparison helpers ---------------------------------------------


    /**
     * Token equality tolerant of display vs file-encoded form on every axis — case-insensitive and
     * dot/space-insensitive, e.g. {@code SDTMIG}=={@code sdtmig}, {@code 3.4}=={@code 3-4},
     * {@code SENDIG-DART}=={@code sendig-dart}. Used for family, standard, and version so a caller
     * may pass either form.
     */
    private static boolean eqTok(String a, String b)
    {
        return a != null && b != null && enc(a).equals(enc(b));
    }


    /**
     * File-name encoding of a token: lower-cased, dots and spaces → dashes ({@code 3.4 → 3-4},
     * {@code SENDIG-DART → sendig-dart}). Shared with the package assembler so the emitted file
     * names and the manifest's version matching use one encoding.
     */
    public static String enc(String token)
    {
        return token.toLowerCase(Locale.ROOT).replace('.', '-').replace(' ', '-');
    }
}
